# Generated by Django 4.2.4 on 2023-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmark_user_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
