# Generated by Django 4.2.4 on 2023-09-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_history_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
